apiVersion: v1
kind: Service
metadata:
  name: es-cluster-svc
  namespace: logging
spec:
  selector: 
    app: elasticsearch
  type: NodePort
  ports:
    - name: rest 
      port: 9200 # 服務端口 
      targetPort: 9200  #應用端口
      nodePort: 32000 #映射到主機的端口30000~32767