apiVersion: v1
kind: Service
metadata:
  name: es-cluster-svc
  namespace: kioxia
  labels:
    app: elasticsearch
spec:
  ports:
    # # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
  - port: 9200
    targetPort: 9200
    # Optional field
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30920
  # 偉了方便測試我們將service設置為NodePort類型
  type: NodePort
  selector:
    app: elasticsearch
