apiVersion: v1
kind: Service
metadata:
  labels:
    kioxia.share.station/server: kioxia-pep
  name: kioxia-public-pep-svc
  namespace: kioxia
spec:
  type: NodePort
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
      nodePort: 30085
      name: kioxia-pep
  selector:
    kioxia.share.station/server: kioxia-pep
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kioxia.share.station/server: kioxia-idp
  name: kioxia-public-idp-svc
  namespace: kioxia
spec:
  type: NodePort
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
      nodePort: 30084
  selector:
    kioxia.share.station/server: kioxia-idp
