---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kioxiafluentdconf
  namespace: kioxia
data:
  fluent.conf: |
      <source>
        @type tail
        path /logs/AccessLog/*.log
        pos_file /var/log/es-containers.log.pos 
        tag app.kioxia.pep.accesslog        # 设置日志标签
        read_from_head true                 # Starts to read the logs from the head of the file or the last read position recorded in pos_file, not tail.
        <parse>
          @type apache2
        </parse>
      </source>

      <filter app.kioxia.pep.accesslog>
        @type record_transformer
        <record>
        hostname ${hostname}
        </record>
      </filter>

      <match app.kioxia.pep.accesslog>
        @type elasticsearch
        host es-cluster-svc
        port 9200
        index_name fluentd.${tag}
        request_timeout    30s
        logstash_format true
        logstash_prefix app.kioxia.pep.accesslog
        flush_interval 1s
      </match>

---
apiVersion: v1
kind: Service
metadata:
  labels:
    kioxia.share.station/server: kioxia-pep
  name: kioxia-public-svc
spec:
  type: NodePort
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
      nodePort: 30085
      name: kioxia-pep
  selector:
    kioxia.share.station/server: kioxia-pep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kioxia-pep
  namespace: kioxia
spec:
  replicas: 1
  selector:
    matchLabels:
      kioxia.share.station/server: kioxia-pep
  template:
    metadata:
      labels:
        kioxia.share.station/server: kioxia-pep
    spec:
      containers:
        - name: kioxia-pep
          image: 192.168.0.100:30004/dev/kioxia-pep:8be6fe9e
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          imagePullPolicy: Always
          name: kioxia-pep
          # 設定想要與同pod container共用的資料夾
          volumeMounts:
            - name: accesslog
              mountPath: /logs/AccessLog/
          ports:
          - containerPort: 8080
            protocol: TCP
      # This is for FluentD Logging Container
        - name: fluentd
          env:
          - name: FLUENT_UID
            value: root
          - name: FLUENT_CONF
            value: fluent.conf
          - name: FLUENTD_ARGS
            value: -c /fluentd/etc/fluent.conf
          image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
          volumeMounts:
          - name: accesslog
            mountPath: /logs/AccessLog/
          - name:  fdconf
            mountPath:  /fluentd/etc/

      volumes:
      - name: accesslog
        emptyDir: {}
      - name: fdconf
        configMap:
          name: kioxiafluentdconf